# parameters:
#   name: xarm_rs_on_hand_calibration
#   calibration_type: eye_in_hand
#   robot_base_frame: link_base
#   robot_effector_frame: link_eef
#   tracking_base_frame: camera_color_optical_frame
#   tracking_marker_frame: camera_marker
#   freehand_robot_movement: true
#   move_group_namespace: /
#   move_group: manipulator
# transform:
#   translation:
#     x: 0.05282033646772982
#     y: 0.04386802728228572
#     z: -0.0017735993904100513
#   rotation:
#     x: -0.006035388725771069
#     y: 0.012037571533873415
#     z: -0.7118858613870623
#     w: 0.7021660710342645

xarm_rs_on_hand_calibration:
  calibration_type: eye_in_hand
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
  transform:
    translation: [0.0528, 0.0439, -0.0018]
    rotation: [-0.0060, 0.0120, -0.7119, 0.7022]
